/*
* To change this template, choose Tools | Templates
* and open the template in the editor.
*/

/*
* dondPanel.java
*
* Created on 11-May-2015, 2:53:55 PM
*/

package dealornodeal;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;



/**
 *
 * @author 333656254
 */
public class dondPanel extends javax.swing.JPanel {
    
    Game game = new Game ();
    private boolean deal= false;
    private boolean exchange = false;
    DecimalFormat dec = new DecimalFormat("#.00");
    
    
    /** Creates new form dondPanel */
    public dondPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        case9 = new javax.swing.JButton();
        case5 = new javax.swing.JButton();
        case1 = new javax.swing.JButton();
        case21 = new javax.swing.JButton();
        case13 = new javax.swing.JButton();
        case17 = new javax.swing.JButton();
        case10 = new javax.swing.JButton();
        case22 = new javax.swing.JButton();
        case14 = new javax.swing.JButton();
        case6 = new javax.swing.JButton();
        case2 = new javax.swing.JButton();
        case18 = new javax.swing.JButton();
        case11 = new javax.swing.JButton();
        case23 = new javax.swing.JButton();
        case15 = new javax.swing.JButton();
        case7 = new javax.swing.JButton();
        case3 = new javax.swing.JButton();
        case19 = new javax.swing.JButton();
        case12 = new javax.swing.JButton();
        case24 = new javax.swing.JButton();
        case16 = new javax.swing.JButton();
        case8 = new javax.swing.JButton();
        case4 = new javax.swing.JButton();
        case20 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 0, 255));

        case9.setText("Case 9");
        case9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case9ActionPerformed(evt);
            }
        });

        case5.setText("Case 5");
        case5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case5ActionPerformed(evt);
            }
        });

        case1.setText("Case 1");
        case1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case1ActionPerformed(evt);
            }
        });

        case21.setText("Case 21");
        case21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case21ActionPerformed(evt);
            }
        });

        case13.setText("Case 13");
        case13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case13ActionPerformed(evt);
            }
        });

        case17.setText("Case 17");
        case17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case17ActionPerformed(evt);
            }
        });

        case10.setText("Case 10");
        case10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case10ActionPerformed(evt);
            }
        });

        case22.setText("Case 22");
        case22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case22ActionPerformed(evt);
            }
        });

        case14.setText("Case 14");
        case14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case14ActionPerformed(evt);
            }
        });

        case6.setText("Case 6");
        case6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case6ActionPerformed(evt);
            }
        });

        case2.setText("Case 2");
        case2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case2ActionPerformed(evt);
            }
        });

        case18.setText("Case 18");
        case18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case18ActionPerformed(evt);
            }
        });

        case11.setText("Case 11");
        case11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case11ActionPerformed(evt);
            }
        });

        case23.setText("Case 23");
        case23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case23ActionPerformed(evt);
            }
        });

        case15.setText("Case 15");
        case15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case15ActionPerformed(evt);
            }
        });

        case7.setText("Case 7");
        case7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case7ActionPerformed(evt);
            }
        });

        case3.setText("Case 3");
        case3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case3ActionPerformed(evt);
            }
        });

        case19.setText("Case 19");
        case19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case19ActionPerformed(evt);
            }
        });

        case12.setText("Case 12");
        case12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case12ActionPerformed(evt);
            }
        });

        case24.setText("Case 24");
        case24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case24ActionPerformed(evt);
            }
        });

        case16.setText("Case 16");
        case16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case16ActionPerformed(evt);
            }
        });

        case8.setText("Case 8");
        case8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case8ActionPerformed(evt);
            }
        });

        case4.setText("Case 4");
        case4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case4ActionPerformed(evt);
            }
        });

        case20.setText("Case 20");
        case20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(case21, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(case17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(case2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(case14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(case3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(case15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(case24, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(case20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(case4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(case4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(case3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(case2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(case1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(case21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void case13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case13ActionPerformed
        this.case13.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(12);
            this.case13.setVisible(false);
        } else {
            game.pickCase(12);
            this.case13.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();        
    }//GEN-LAST:event_case13ActionPerformed

    private void case14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case14ActionPerformed
        this.case14.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(13);
            this.case14.setVisible(false);
        } else {
            game.pickCase(13);
            this.case14.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case14ActionPerformed

    private void case15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case15ActionPerformed
        this.case15.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(14);
            this.case15.setVisible(false);
        } else {
            game.pickCase(14);
            this.case15.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case15ActionPerformed

    private void case16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case16ActionPerformed
        this.case16.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(15);
            this.case16.setVisible(false);
        } else {
            game.pickCase(15);
            this.case16.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case16ActionPerformed

    private void case1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case1ActionPerformed
        this.case1.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(0);
            this.case1.setVisible(false);
        } else {
            game.pickCase(0);
            this.case1.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case1ActionPerformed

    private void case2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case2ActionPerformed
        this.case2.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(1);
            this.case2.setVisible(false);
        } else {
            game.pickCase(1);
            this.case2.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case2ActionPerformed

    private void case3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case3ActionPerformed
        this.case3.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(2);
            this.case3.setVisible(false);
        } else {
            game.pickCase(2);
            this.case3.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case3ActionPerformed

    private void case4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case4ActionPerformed
        this.case4.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(3);
            this.case4.setVisible(false);
        } else {
            game.pickCase(3);
            this.case4.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case4ActionPerformed

    private void case5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case5ActionPerformed
        this.case5.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(4);
            this.case5.setVisible(false);
        } else {
            game.pickCase(4);
            this.case5.setText("" + game.getMoney());
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case5ActionPerformed

    private void case6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case6ActionPerformed
        this.case6.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(5);
            this.case6.setVisible(false);
        } else {
            game.pickCase(5);
            this.case6.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case6ActionPerformed

    private void case7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case7ActionPerformed
        this.case7.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(6);
            this.case7.setVisible(false);
        } else {
            game.pickCase(6);
            this.case7.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case7ActionPerformed

    private void case8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case8ActionPerformed
        this.case8.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(7);
            this.case8.setVisible(false);
        } else {
            game.pickCase(7);
            this.case8.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case8ActionPerformed

    private void case9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case9ActionPerformed
        this.case9.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(8);
            this.case9.setVisible(false);
        } else {
            game.pickCase(8);
            this.case9.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case9ActionPerformed

    private void case10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case10ActionPerformed
        this.case10.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(9);
            this.case10.setVisible(false);
        } else {
            game.pickCase(9);
            this.case10.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case10ActionPerformed

    private void case11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case11ActionPerformed
        this.case11.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(10);
            this.case11.setVisible(false);
        } else {
            game.pickCase(10);
            this.case11.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case11ActionPerformed

    private void case12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case12ActionPerformed
        this.case12.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(11);
            this.case12.setVisible(false);
        } else {
            game.pickCase(11);
            this.case12.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case12ActionPerformed

    private void case17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case17ActionPerformed
        this.case17.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(16);
            this.case17.setVisible(false);
        } else {
            game.pickCase(16);
            this.case17.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case17ActionPerformed

    private void case18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case18ActionPerformed
        this.case18.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(17);
            this.case18.setVisible(false);
        } else {
            game.pickCase(17);
            this.case18.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case18ActionPerformed

    private void case19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case19ActionPerformed
        this.case19.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(18);
            this.case19.setVisible(false);
        } else {
            game.pickCase(18);
            this.case19.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case19ActionPerformed

    private void case20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case20ActionPerformed
        this.case20.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(19);
            this.case20.setVisible(false);
        } else {
            game.pickCase(19);
            this.case20.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case20ActionPerformed

    private void case21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case21ActionPerformed
        this.case21.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(20);
            this.case21.setVisible(false);
        } else {
            game.pickCase(20);
            this.case21.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case21ActionPerformed

    private void case22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case22ActionPerformed
        this.case22.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(21);
            this.case22.setVisible(false);
        } else {
            game.pickCase(21);
            this.case22.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case22ActionPerformed

    private void case23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case23ActionPerformed
        this.case23.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(22);
            this.case23.setVisible(false);
        } else {
            game.pickCase(22);
            this.case23.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case23ActionPerformed

    private void case24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case24ActionPerformed
        this.case24.setEnabled(false);
        if (game.getRound() == 0) {
            game.yourCase(23);
            this.case24.setVisible(false);
        } else {
            game.pickCase(23);
            this.case24.setText("" + dec.format(game.getMoney()));
            if (game.getRound() == 6 || game.getRound() == 11 || game.getRound() == 15 || game.getRound() == 19 || game.getRound() == 21 || game.getRound() == 23) {
                offer();
            }
        }
        this.repaint();
    }//GEN-LAST:event_case24ActionPerformed
    
    public void offer () {
        double offer = game.makeOffer();
        // double realOffer = Double.valueOf();
        Object[] options = {"DEAL", "NO DEAL"};
        int n = JOptionPane.showOptionDialog(this, "$" + dec.format(offer), "BANK OFFER", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, //do not use a custom Icon
                options,  //the titles of buttons
                options[0]); //default button title
        if (n == 0) {
            this.deal = true;
        } else if (n == 1 && game.getRound() == 23) {
            Object[] option = {"Yes", "No"};
            int m = JOptionPane.showOptionDialog(this, "Would you like to exchange your case?", "EXCHANGE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, //do not use a custom Icon
                option,  //the titles of buttons
                option[0]); //default button title
            if (m == 0) {
                this.exchange = true;
                int initialCase = game.getYourCase() + 1;
                game.exchangeCase(game.caseRemaining());
                if (game.getRemaining(0)) {
                this.case1.setText("Case " + initialCase);
                } else if (game.getRemaining(1)) {
                this.case2.setText("Case " + initialCase);
                } else if (game.getRemaining(2)) {
                this.case3.setText("Case " + initialCase);
                } else if (game.getRemaining(3)) {
                this.case4.setText("Case " + initialCase);
                } else if (game.getRemaining(4)) {
                this.case5.setText("Case " + initialCase);
                } else if (game.getRemaining(5)) {
                this.case6.setText("Case " + initialCase);
                } else if (game.getRemaining(6)) {
                this.case7.setText("Case " + initialCase);
                } else if (game.getRemaining(7)) {
                this.case8.setText("Case " + initialCase);
                } else if (game.getRemaining(8)) {
                this.case9.setText("Case " + initialCase);
                } else if (game.getRemaining(9)) {
                this.case10.setText("Case " + initialCase);
                } else if (game.getRemaining(10)) {
                this.case11.setText("Case " + initialCase);
                } else if (game.getRemaining(11)) {
                this.case12.setText("Case " + initialCase);
                } else if (game.getRemaining(12)) {
                this.case13.setText("Case " + initialCase);
                } else if (game.getRemaining(13)) {
                this.case14.setText("Case " + initialCase);
                } else if (game.getRemaining(14)) {
                this.case15.setText("Case " + initialCase);
                } else if (game.getRemaining(15)) {
                this.case16.setText("Case " + initialCase);
                } else if (game.getRemaining(16)) {
                this.case17.setText("Case " + initialCase);
                } else if (game.getRemaining(17)) {
                this.case18.setText("Case " + initialCase);
                } else if (game.getRemaining(18)) {
                this.case19.setText("Case " + initialCase);
                } else if (game.getRemaining(19)) {
                this.case20.setText("Case " + initialCase);
                } else if (game.getRemaining(20)) {
                this.case21.setText("Case " + initialCase);
                } else if (game.getRemaining(21)) {
                this.case22.setText("Case " + initialCase);
                } else if (game.getRemaining(22)) {
                this.case23.setText("Case " + initialCase);
                } else if (game.getRemaining(23)) {
                this.case24.setText("Case " + initialCase);
                }
                this.repaint();
            }
        }
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        for (int i = 0; i < 12; i++) {
            g.setColor(Color.green);
            g.fillRect(600, 60 + 25*i, 100, 24);
            g.fillRect(725, 60 + 25*i, 100, 24);
            g.setColor(Color.black);
            g.drawRect(600, 60 + 25*i, 100, 24);
            g.drawRect(725, 60 + 25*i, 100, 24);
        }
        
        g.setColor(Color.red);
        if (game.isRemaining(.01) == false) {
            g.fillRect(600, 60, 100, 24);
        }
        if (game.isRemaining(1) == false) {
            g.fillRect(600, 85, 100, 24);
        }
        if (game.isRemaining(5) == false) {
            g.fillRect(600, 110, 100, 24);
        }
        if (game.isRemaining(10) == false) {
            g.fillRect(600, 135, 100, 24);
        }
        if (game.isRemaining(25) == false) {
            g.fillRect(600, 160, 100, 24);
        }
        if (game.isRemaining(50) == false) {
            g.fillRect(600, 185, 100, 24);
        }
        if (game.isRemaining(100) == false) {
            g.fillRect(600, 210, 100, 24);
        }
        if (game.isRemaining(200) == false) {
            g.fillRect(600, 235, 100, 24);
        }
        if (game.isRemaining(300) == false) {
            g.fillRect(600, 260, 100, 24);
        }
        if (game.isRemaining(500) == false) {
            g.fillRect(600, 285, 100, 24);
        }
        if (game.isRemaining(750) == false) {
            g.fillRect(600, 310, 100, 24);
        }
        if (game.isRemaining(1000) == false) {
            g.fillRect(600, 335, 100, 24);
        }
        if (game.isRemaining(5000) == false) {
            g.fillRect(725, 60, 100, 24);
        }
        if (game.isRemaining(10000) == false) {
            g.fillRect(725, 85, 100, 24);
        }
        if (game.isRemaining(25000) == false) {
            g.fillRect(725, 110, 100, 24);
        }
        if (game.isRemaining(50000) == false) {
            g.fillRect(725, 135, 100, 24);
        }
        if (game.isRemaining(75000) == false) {
            g.fillRect(725, 160, 100, 24);
        }
        if (game.isRemaining(100000) == false) {
            g.fillRect(725, 185, 100, 24);
        }
        if (game.isRemaining(200000) == false) {
            g.fillRect(725, 210, 100, 24);
        }
        if (game.isRemaining(300000) == false) {
            g.fillRect(725, 235, 100, 24);
        }
        if (game.isRemaining(400000) == false) {
            g.fillRect(725, 260, 100, 24);
        }
        if (game.isRemaining(500000) == false) {
            g.fillRect(725, 285, 100, 24);
        }
        if (game.isRemaining(750000) == false) {
            g.fillRect(725, 310, 100, 24);
        }
        if (game.isRemaining(1000000) == false) {
            g.fillRect(725, 335, 100, 24);
        }
        g.setColor(Color.black);
        g.drawString("$0.01", 633, 77);
        g.drawString("$1.00", 633, 102);
        g.drawString("$5.00", 633, 127);
        g.drawString("$10.00", 630, 152);
        g.drawString("$25.00", 630, 177);
        g.drawString("$50.00", 630, 202);
        g.drawString("$100.00", 627, 227);
        g.drawString("$200.00", 627, 252);
        g.drawString("$300.00", 627, 277);
        g.drawString("$500.00", 627, 302);
        g.drawString("$750.00", 627, 327);
        g.drawString("$1000.00", 624, 352);
        g.drawString("$5000.00", 749, 77);
        g.drawString("$10000.00", 746, 102);
        g.drawString("$25000.00", 746, 127);
        g.drawString("$50000.00", 746, 152);
        g.drawString("$75000.00", 746, 177);
        g.drawString("$100000.00", 743, 202);
        g.drawString("$200000.00", 743, 227);
        g.drawString("$300000.00", 743, 252);
        g.drawString("$400000.00", 743, 277);
        g.drawString("$500000.00", 743, 302);
        g.drawString("$750000.00", 743, 327);
        g.drawString("$1000000.00", 740, 352);
        
        g.setColor(Color.yellow);
        Font titleFont = new Font ("Arial", Font.BOLD, 36);
        g.setFont(titleFont);
        g.drawString("DEAL OR NO DEAL", 550, 40);
        
        if (this.exchange) {
            Font font = new Font ("Arial", Font.BOLD, 34);
            g.setFont(font);
            System.out.println(game.getYourCase());
            g.drawString("YOUR CASE: Case " + (game.getYourCase() + 1), 60, 370);
        } else if(game.getRound() > 0) {
            Font font = new Font ("Arial", Font.BOLD, 34);
            g.setFont(font);            
            g.drawString("YOUR CASE: Case " + (game.getYourCase() + 1),60,370);
        }
        
        if (this.deal || game.getRound() == 24) {
            Font newfont = new Font ("Arial", Font.BOLD, 30);
            g.setFont(newfont);
            this.case1.setVisible(false);
            this.case2.setVisible(false);
            this.case3.setVisible(false);
            this.case4.setVisible(false);
            this.case5.setVisible(false);
            this.case6.setVisible(false);
            this.case7.setVisible(false);
            this.case8.setVisible(false);
            this.case9.setVisible(false);
            this.case10.setVisible(false);
            this.case11.setVisible(false);
            this.case12.setVisible(false);
            this.case13.setVisible(false);
            this.case14.setVisible(false);
            this.case15.setVisible(false);
            this.case16.setVisible(false);
            this.case17.setVisible(false);
            this.case20.setVisible(false);
            this.case18.setVisible(false);
            this.case19.setVisible(false);
            this.case21.setVisible(false);
            this.case22.setVisible(false);
            this.case23.setVisible(false);
            this.case24.setVisible(false);
            g.setColor(Color.yellow);
            g.fillRect(0,0,950,600);
            g.setColor(Color.blue);
            if (this.deal) {                
                g.drawString("CONGRATULATIONS! YOU WALKED AWAY WITH $" + dec.format(game.makeOffer()), 30, 200);
            } else {                
                g.drawString("YOUR CASE HAS $" + dec.format(game.getMoney(game.getYourCase())), 310, 200);
            }
        }
        
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton case1;
    private javax.swing.JButton case10;
    private javax.swing.JButton case11;
    private javax.swing.JButton case12;
    private javax.swing.JButton case13;
    private javax.swing.JButton case14;
    private javax.swing.JButton case15;
    private javax.swing.JButton case16;
    private javax.swing.JButton case17;
    private javax.swing.JButton case18;
    private javax.swing.JButton case19;
    private javax.swing.JButton case2;
    private javax.swing.JButton case20;
    private javax.swing.JButton case21;
    private javax.swing.JButton case22;
    private javax.swing.JButton case23;
    private javax.swing.JButton case24;
    private javax.swing.JButton case3;
    private javax.swing.JButton case4;
    private javax.swing.JButton case5;
    private javax.swing.JButton case6;
    private javax.swing.JButton case7;
    private javax.swing.JButton case8;
    private javax.swing.JButton case9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    // End of variables declaration//GEN-END:variables
    
}
